In [369]:
import pandas as pd

file_path = 'C:/Users/SIYA/Downloads/DAV_CA_data/life_expectancy_data.csv'
data = pd.read_csv(file_path)

In [370]:
data.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [371]:
data.describe()
# there are missing values since count of columns is different should be 2938 for all 
# also from min max values we see data needs to be scaled

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [372]:
#check data types of cols
column_data_types = data.dtypes
print(column_data_types)

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [373]:
# Create a new binary column based on the "Status" column
data['Country_Status'] = data['Status'].apply(lambda x: 1 if x == 'Developed' else 0)

# Drop the original "Status" column 
data.drop('Status', axis=1, inplace=True)
print(data.columns)

Index(['Country', 'Year', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Country_Status'],
      dtype='object')

In [374]:
#check missing values
missing_values = data.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Country                              0
Year                                 0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
Country_Status                       0
dtype: int64

In [375]:
#focusing on only european countries
# List of European countries
european_countries = [
    "Albania", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
    "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Georgia", "Germany", "Greece",
    "Hungary", "Iceland", "Ireland", "Italy", "Kazakhstan", "Kosovo", "Latvia", "Lithuania", "Luxembourg", "Malta",
    "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania",
    "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "Ukraine",
    "United Kingdom", "Vatican City"
]

# Filter out European countries
data = data[data['Country'].isin(european_countries)]

In [376]:
# cleaning data

# Check if the country has data for each year from 2000 to 2015

countries_to_delete = []  
for country in data['Country'].unique():
    years = data[data['Country'] == country]['Year'].unique()
    if set(range(2000, 2016)).difference(years):
        print(f"{country} is missing data for the following years:", end=" ")
        missing_years = set(range(2000, 2016)).difference(years)
        print(missing_years)
        countries_to_delete.append(country)

Monaco is missing data for the following years: {2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2014, 2015}
San Marino is missing data for the following years: {2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2014, 2015}

In [377]:
#delete above country rows since they have data only for the year 2013
data = data[~data['Country'].isin(countries_to_delete)]

In [378]:
#POPULATION MISSING VALUES

#read population data and fill missing values for current data
file_path = 'C:/Users/SIYA/Downloads/EDU_DEM_03052024202813726.csv'
population_data = pd.read_csv(file_path)

In [379]:
# Function to fill missing population values
def fill_missing_population(row):
    year = row['Year']
    country = row['Country']
    population_value = row['Population']
    if pd.isnull(population_value):  # Check if the population value is missing
        matching_population = population_data[(population_data['Country'] == country) & (population_data['YEAR'] == year)]['Value'].values
        if len(matching_population) > 0:
            return matching_population[0]
    return population_value  # Return the original value if it's not missing

# Apply the function to fill missing values in the Population column
data['Population'] = data.apply(fill_missing_population, axis=1)

print(data)

      Country  Year  Life expectancy   Adult Mortality  infant deaths  \
16    Albania  2015              77.8             74.0              0
17    Albania  2014              77.5              8.0              0
18    Albania  2013              77.2             84.0              0
19    Albania  2012              76.9             86.0              0
20    Albania  2011              76.6             88.0              0
...       ...   ...               ...              ...            ...
2741  Ukraine  2004              67.4            267.0              5
2742  Ukraine  2003              67.6            256.0              6
2743  Ukraine  2002              67.6            256.0              6
2744  Ukraine  2001              67.7            253.0              6
2745  Ukraine  2000              67.5            257.0              6

      Alcohol  percentage expenditure  Hepatitis B  Measles    BMI   ...  \
16       4.60              364.975229         99.0         0   58.0  ...
17       4.51              428.749067         98.0         0   57.2  ...
18       4.76              430.876979         99.0         0   56.5  ...
19       5.14              412.443356         99.0         9   55.8  ...
20       5.37              437.062100         99.0        28   55.1  ...
...       ...                     ...          ...       ...    ...  ...
2741     6.79              180.353786         98.0       146   56.1  ...
2742     5.92               21.223864         77.0       411   55.7  ...
2743     4.89              115.738974         48.0      7587   55.4  ...
2744     4.31                8.897421          7.0     16970   55.1  ...
2745     4.49                7.883791          4.0       817   54.8  ...

      Total expenditure  Diphtheria    HIV/AIDS          GDP  Population  \
16                 6.00         99.0        0.1  3954.227830     28873.0
17                 5.88         98.0        0.1  4575.763787    288914.0
18                 5.66         99.0        0.1  4414.723140    289592.0
19                 5.59         99.0        0.1  4247.614380      2941.0
20                 5.71         99.0        0.1  4437.178680    295195.0
...                 ...          ...        ...          ...         ...
2741               6.61         99.0        1.0  1367.352433    474516.0
2742               6.93         97.0        0.9   148.522488   4781295.0
2743               6.25         99.0        0.9   879.475486     48225.0
2744               5.66         99.0        0.8    78.738243  48683865.0
2745               5.59         99.0        0.7   635.789635  49175848.0

       thinness  1-19 years   thinness 5-9 years  \
16                      1.2                  1.3
17                      1.2                  1.3
18                      1.3                  1.4
19                      1.3                  1.4
20                      1.4                  1.5
...                     ...                  ...
2741                    2.7                  2.8
2742                    2.8                  2.9
2743                    2.9                  3.0
2744                    2.9                  3.0
2745                    3.0                  3.1

      Income composition of resources  Schooling  Country_Status
16                              0.762       14.2               0
17                              0.761       14.2               0
18                              0.759       14.2               0
19                              0.752       14.2               0
20                              0.738       13.3               0
...                               ...        ...             ...
2741                            0.700       14.6               0
2742                            0.691       14.3               0
2743                            0.683       13.9               0
2744                            0.673       13.2               0
2745                            0.669       13.3               0

[656 rows x 22 columns]

In [380]:
# for countries not in population data fill using dict obtained from - https://www.macrotrends.net/global-metrics/countries/SGP/<country-name>/population 
# replace <country-name> with country name

# Define a dictionary to map countries to their population data
population_dict = {
    'Czechia': {
        2009: 10421510,
        2008: 10378583,
        2007: 10337829,
        2006: 10304815,
        2004: 10260999,
        2003: 10248038,
        2002: 10238170,
        2001: 10230276
    },
    'Slovakia': {
        2015: 5424444,
        2014: 5419569,
        2013: 5414739,
        2012: 5409283,
        2011: 5402680,
        2010: 5396424,
        2009: 5388926,
        2008: 5381636,
        2007: 5378382,
        2006: 5377235,
        2005: 5376242,
        2004: 5374931,
        2003: 5374376,
        2002: 5375206,
        2001: 5376456,
        2000: 5376690
    }
}

# Fill missing population values based on the dictionary
for index, row in data.iterrows():
    if pd.isnull(row['Population']):
        country = row['Country']
        year = row['Year']
        if country in population_dict and year in population_dict[country]:
            data.at[index, 'Population'] = population_dict[country][year]

In [381]:
#data.to_csv('european_data.csv', index=False)
#check missing values
missing_values = data.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Country                              0
Year                                 0
Life expectancy                      0
Adult Mortality                      0
infant deaths                        0
Alcohol                             40
percentage expenditure               0
Hepatitis B                        176
Measles                              0
 BMI                                 0
under-five deaths                    0
Polio                                6
Total expenditure                   40
Diphtheria                           6
 HIV/AIDS                            0
GDP                                 32
Population                           0
 thinness  1-19 years                0
 thinness 5-9 years                  0
Income composition of resources     16
Schooling                           16
Country_Status                       0
dtype: int64

In [382]:
#Hepatitis B MISSING VALUES

# countries with all missing Hepatitis B values
countries_with_missing_hep_b = set()

def fill_missing_hepatitis_b(row):
    global countries_with_missing_hep_b
    country = row['Country']
    hep_b_values = data[data['Country'] == country]['Hepatitis B']
    if hep_b_values.isnull().all() and country not in countries_with_missing_hep_b:
        print(f"All Hepatitis B values missing for {country}")
        countries_with_missing_hep_b.add(country)
    elif not hep_b_values.isnull().all():
        country_mean = hep_b_values.mean()
        row['Hepatitis B'] = country_mean
    return row

#fill missing values in the Hepatitis B column
data = data.apply(fill_missing_hepatitis_b, axis=1)

All Hepatitis B values missing for Denmark
All Hepatitis B values missing for Finland
All Hepatitis B values missing for Hungary
All Hepatitis B values missing for Iceland
All Hepatitis B values missing for Norway
All Hepatitis B values missing for Slovenia
All Hepatitis B values missing for Switzerland

In [383]:
#for countries with missing values for all years for hepatits B
#found from - https://med.stanford.edu/liver/research/global-vaccination-coverage.html 

# Manually set Hepatitis B values for specific countries
hepatitis_b_values = {
    'Finland': 2,
    'Denmark': 2,
    'Hungary': 2,
    'Iceland': 2,
    'Norway': 96,
    'Slovenia': 2,
    'Switzerland': 72
}
data.loc[data['Country'].isin(hepatitis_b_values.keys()), 'Hepatitis B'] = data['Country'].map(hepatitis_b_values)

In [384]:
def fill_missing_alcohol(row):
    country = row['Country']
    alcohol_values = data[(data['Country'] == country) & data['Alcohol'].notna()]['Alcohol']
    if alcohol_values.any():  # Check if any non-missing values exist for the country
        country_mean = alcohol_values.mean()
        row['Alcohol'] = row['Alcohol'] if not pd.isna(row['Alcohol']) else country_mean
    return row

# Apply the function to fill missing values in the Alcohol column
data = data.apply(fill_missing_alcohol, axis=1)

# Check missing values
missing_values = data.isnull().sum()
print("Missing Values:\n", missing_values)

# Check if conversion was successful
print(data['Alcohol'].dtype)

Missing Values:
 Country                             0
Year                                0
Life expectancy                     0
Adult Mortality                     0
infant deaths                       0
Alcohol                             0
percentage expenditure              0
Hepatitis B                         0
Measles                             0
 BMI                                0
under-five deaths                   0
Polio                               6
Total expenditure                  40
Diphtheria                          6
 HIV/AIDS                           0
GDP                                32
Population                          0
 thinness  1-19 years               0
 thinness 5-9 years                 0
Income composition of resources    16
Schooling                          16
Country_Status                      0
dtype: int64
float64

In [385]:
# replace missing values for Total expenditure, Polio, GDP, Diphtheria, Income composition of resources, Schooling with mean of each column since very small amount of data missing (<35 rows)      

columns_to_fill = ['Total expenditure', 'Polio', 'GDP', 'Diphtheria ', 'Income composition of resources', 'Schooling']

# Iterate through each column and fill missing values with column mean
for col in columns_to_fill:
    data[col].fillna(data[col].mean(), inplace=True)

In [391]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Define columns to scale
columns_to_scale = [col for col in data.columns if col not in ['Country', 'Year', 'Country_Status',' HIV/AIDS']]

# Fit and transform each selected column
for col in columns_to_scale:
    scaler.fit(data[[col]])
    data[col] = scaler.transform(data[col].values.reshape(-1, 1))

c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\SIYA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

In [392]:
data.head()
#data.to_csv('processed_data.csv', index=False)

,Country,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Country_Status
16,Albania,2015,0.554,0.248,0.0,0.257,0.019,0.994,0.000,0.820,...,0.451,1.000,0.1,0.033,0.000,0.18,0.22,0.804,0.740,0
17,Albania,2014,0.542,0.024,0.0,0.252,0.022,0.994,0.000,0.808,...,0.440,0.989,0.1,0.038,0.004,0.18,0.22,0.803,0.740,0
18,Albania,2013,0.530,0.282,0.0,0.266,0.022,0.994,0.000,0.797,...,0.420,1.000,0.1,0.037,0.004,0.20,0.24,0.801,0.740,0
19,Albania,2012,0.518,0.289,0.0,0.287,0.021,0.994,0.000,0.786,...,0.413,1.000,0.1,0.036,0.000,0.20,0.24,0.793,0.740,0
20,Albania,2011,0.506,0.296,0.0,0.300,0.022,0.994,0.001,0.775,...,0.424,1.000,0.1,0.037,0.004,0.22,0.26,0.778,0.693,0